name: Image builds

on:
  push:
    paths:
      - ".github/workflows/build.yaml"
      - "src/**"
  schedule:
    - cron: "0 21 * * 0"
  workflow_dispatch:

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: version
        working-directory: ./src
        run: |
          docker-compose -f compose.yml -f amd64.yml build --pull
          docker-compose -f compose.yml -f amd64.yml push


  build-linux-arm64:
    runs-on: [self-hosted, linux, arm64, docker]
    steps:
      - uses: actions/checkout@master  

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: version
        working-directory: ./src
        run: |
          docker-compose -f compose.yml -f arm64.yml build --pull
          docker-compose -f compose.yml -f arm64.yml push
